# Generated by Django 3.2.3 on 2021-05-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210521_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplier',
            name='GST_no',
            field=models.IntegerField(default=123),
        ),
    ]
