# Generated by Django 3.2.3 on 2021-06-09 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_suplier_gst_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catergory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
                ('suplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.suplier')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bname', models.CharField(max_length=50)),
                ('Bprice', models.CharField(max_length=50)),
                ('Bdescription', models.CharField(max_length=150)),
                ('stock', models.CharField(default='available', max_length=50)),
                ('Bimg', models.ImageField(upload_to='img/')),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now_add=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.catergory')),
            ],
        ),
    ]
