# Generated by Django 3.2.3 on 2021-06-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_addproduct_sup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='Bdescription',
            field=models.CharField(max_length=500),
        ),
    ]
