# Generated by Django 3.2.3 on 2021-06-29 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_addproduct_bdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QTY', models.IntegerField(max_length=50)),
                ('Total', models.IntegerField(max_length=50)),
                ('Subtotal', models.IntegerField(max_length=50)),
                ('addpro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.addproduct')),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
    ]
